# site settings

title: Bjørn Andreas Andersen
description: Makerspace designer
taglong: Digital business card
tagshort: Digital business card
url: https://polybjorn.com
baseurl: ""
permalink: pretty
repo: https://github.com/polybjorn/polybjorn.github.io

# author settings

author:
  name: Bjørn Andreas Andersen
  email: bjanda@pm.me
photo: /assets/jpg/photo.jpg

# social media links

social:
  grabcad: bjorn.andreas.andersen-2
  github: polybjorn

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
