// CV Template — Polybjorn
// Usage: typst compile cv/template.typ cv/output/cv-en.pdf --input lang=en --font-path cv/fonts --root .
//        typst compile cv/template.typ cv/output/cv-no.pdf --input lang=no --font-path cv/fonts --root .

// --- Configuration ---

#let lang = sys.inputs.at("lang", default: "en")
#let data = yaml("../src/data/cv.yaml")
#let contact = yaml("../src/data/contact.yaml")

#let labels = (
  en: (
    experience: "Experience",
    education: "Education",
    skills: "Skills",
    software: "Software skills",
    at-org: "for",
  ),
  no: (
    experience: "Arbeidserfaring",
    education: "Utdannelse",
    skills: "Ferdigheter",
    software: "Programvare",
    at-org: "hos",
  ),
)

#let label = labels.at(lang)

// --- Brand colors ---

#let color-body = rgb("#111111")
#let color-muted = rgb("#8A8F99")
#let color-box-bg = rgb("#e8e8ee")
#let section-gap = 24pt

// --- Page setup ---

#set page(
  paper: "a4",
  margin: (top: 15mm, bottom: 15mm, left: 20mm, right: 20mm),
)

#set text(
  font: "Liberation Sans",
  size: 8.5pt,
  fill: color-body,
)

#set par(
  leading: 0.75em,
  justify: false,
)

// --- Heading styles ---

#show heading.where(level: 1): it => {
  set text(size: 24pt, weight: "bold", fill: color-body)
  block(above: 0pt, below: 2pt, it.body)
}

#show heading.where(level: 2): it => {
  set text(size: 11pt, weight: "bold", fill: color-body)
  block(above: 0pt, below: 6pt, it.body)
}

// --- Helper functions ---

#let experience-entry(title: "", org: "", period: "", desc: none, prep: "for") = {
  block(above: 14pt, below: 0pt, {
    grid(
      columns: (72pt, 1fr),
      gutter: 10pt,
      text(size: 8pt, fill: color-muted, period),
      {
        text(weight: "bold", size: 8.5pt)[#title #prep #org]
        if desc != none {
          linebreak()
          text(fill: color-body, size: 8pt, desc)
        }
      },
    )
  })
}

#let education-entry(title: "", org: "", period: "") = {
  block(above: 12pt, below: 0pt, {
    grid(
      columns: (72pt, 1fr),
      gutter: 10pt,
      text(size: 8pt, fill: color-muted, period),
      {
        text(weight: "bold", size: 8.5pt, org)
        linebreak()
        text(size: 8pt, fill: color-body, title)
      },
    )
  })
}

// Icon lists generated by build.sh from cv/icons/ directory
#let icon-manifest = json("icons.json")
#let icons-available = icon-manifest.at("svg", default: ())
#let icons-png = icon-manifest.at("png", default: ())

// Tool names that don't work as filenames (e.g. slashes)
#let icon-filename-map = (
  "HTML/CSS": "HTML-CSS",
)

#let software-box(category, tools) = {
  let tool-grid(tool-render) = {
    align(center, text(weight: "bold", size: 8.5pt, fill: color-body, category))
    v(4pt)
    let cols = calc.min(tools.len(), 6)
    grid(
      columns: (1fr,) * cols,
      row-gutter: 4pt,
      column-gutter: 4pt,
      ..tools.map(tool => align(center, {
        tool-render(tool)
        linebreak()
        v(1pt)
        text(size: 6.5pt, fill: color-body, tool)
      }))
    )
  }
  block(above: 10pt, width: 100%, {
    // Shadow: hidden duplicate sized identically to main box
    place(dx: 1.5pt, dy: 1.5pt, block(
      width: 100%,
      fill: luma(180),
      radius: 4pt,
      inset: (x: 10pt, y: 8pt),
      hide(tool-grid(tool => box(width: 18pt, height: 18pt)))
    ))
    block(
      width: 100%,
      fill: color-box-bg,
      radius: 4pt,
      stroke: 0.5pt + luma(200),
      inset: (x: 10pt, y: 8pt),
      tool-grid(tool => {
        let filename = icon-filename-map.at(tool, default: tool)
        if tool in icons-available or tool in icon-filename-map {
          box(width: 18pt, height: 18pt, image("icons/" + filename + ".svg", width: 100%, height: 100%, fit: "contain"))
        } else if tool in icons-png {
          box(width: 18pt, height: 18pt, image("icons/" + filename + ".png", width: 100%, height: 100%, fit: "contain"))
        } else {
          box(width: 18pt, height: 18pt, fill: luma(220), radius: 2pt)
        }
      })
    )
  })
}

// ============================================================
// PAGE 1
// ============================================================

// --- Header: Name + Photo ---

#let personal = contact.personal.at(lang)

#grid(
  columns: (1fr, 100pt),
  gutter: 60pt,
  {
    heading(level: 1)[Bjørn Andreas Andersen]
    block(above: 12pt, text(size: 9pt, fill: color-body, personal.born))
    block(above: 8pt, text(size: 9pt, fill: color-body, personal.address))
    v(24pt)
    block(text(size: 8.5pt, fill: color-body, data.profile.at(lang)))
  },
  {
    box(
      width: 100pt,
      height: 100pt,
      radius: 50pt,
      clip: true,
      image("images/profile-photo.png", width: 100pt, height: 100pt),
    )
    v(8pt)
    align(center, {
      text(size: 9.5pt, contact.phone)
      linebreak()
      text(size: 9.5pt, contact.email)
      linebreak()
      text(size: 9.5pt, contact.website.at(lang))
    })
  },
)

// --- Education + Skills ---

#v(section-gap)
#grid(
  columns: (1fr, 1fr),
  gutter: 24pt,
  {
    heading(level: 2)[#label.education]
    for item in data.education {
      let loc = item.at(lang)
      let p = item.period
      let period = if type(p) == dictionary { p.at(lang) } else { p }
      education-entry(
        title: loc.title,
        org: loc.org,
        period: period,
      )
    }
  },
  {
    heading(level: 2)[#label.skills]
    {
      let skills = data.skills.filter(s => s.at("cv", default: true))
      for (i, skill) in skills.enumerate() {
        block(above: 6pt, below: 0pt, [· #skill.at(lang)])
      }
    }
  },
)

// --- Experience ---

#v(section-gap)
== #label.experience

#for item in data.experience {
  let loc = item.at(lang)
  let p = item.period
  let period = if type(p) == dictionary { p.at(lang) } else { p }
  experience-entry(
    title: loc.title,
    org: loc.org,
    period: period,
    desc: loc.at("desc", default: none),
    prep: label.at-org,
  )
}

// --- Certifications + References ---

#let certs = data.certifications.at(lang)

#v(section-gap)

== #certs.title

#{
  let items = certs.items
  for (i, item) in items.enumerate() {
    [· #item]
    if i < items.len() - 1 { [\ ] }
  }
}

#v(1fr)
#align(right, text(style: "italic", fill: color-muted, size: 9pt, data.references.at(lang)))

// ============================================================
// PAGE 2
// ============================================================

#pagebreak()

// --- Software Skills ---

#align(center, heading(level: 2)[#label.software])

#v(8pt)

#for cat in data.software.filter(c => c.at("cv", default: true)) {
  let tools = cat.at("cv_tools", default: cat.tools)
  software-box(cat.category.at(lang), tools)
}

// --- Client List ---

#v(section-gap)

#let client-data = data.clients
#align(center, heading(level: 2)[#client-data.at(lang).title])

#v(4pt)

#{
  let items = client-data.list
  let cols = 3
  let rows = calc.ceil(items.len() / cols)
  let cells = ()
  for i in range(rows) {
    for c in range(cols) {
      let idx = i * cols + c
      if idx < items.len() {
        cells.push(align(center, text(size: 8.5pt, items.at(idx))))
      } else {
        cells.push([])
      }
    }
  }
  grid(
    columns: (1fr, 1fr, 1fr),
    row-gutter: 8pt,
    column-gutter: 16pt,
    ..cells,
  )
}
